name: castersoundboard 
version: "0.0.1+git"
summary: A soundboard for hot-keying and playing back sounds. (For podcasting)
description: A soundboard for hot-keying and playing back sounds. (For podcasting)
grade: devel
confinement: devmode

apps:
  castersoundboard:
    command: bin/CasterSoundboard

parts:
  main:
    source: ./CasterSoundboard
    plugin: qmake
    qt-version: qt5
    build-packages:
      - qtdeclarative5-dev
      - qt5-default
      - qtmultimedia5-dev
      - build-essential
