name: castersoundboard
version: git
summary: A soundboard for hot-keying and playing back sounds. (For podcasting)
description: A soundboard for hot-keying and playing back sounds. (For podcasting)

grade: stable
confinement: devmode

parts:
  main:
    source: ./CasterSoundboard
    plugin: qmake
    qt-version: qt5
    after:
      - desktop-qt5
    build-packages:
      - g++
      - qtdeclarative5-dev
      - qt5-default
      - qtmultimedia5-dev

apps:
  castersoundboard:
    command: bin/desktop-launch $SNAP/bin/CasterSoundboard
    #command: env TMPDIR=$XDG_RUNTIME_DIR PATH=/usr/local/bin:${PATH} ${SNAP}/bin/desktop-launch $SNAP/usr/share/wpcom/wpcom
    #desktop: usr/share/applications/wpcom.desktop
    plugs:
      #- gsettings
      - home
      - mount-observe
      - network
      - pulseaudio
      #- unity7
      - x11
