name: castersoundboard
version: git
summary: A soundboard for hot-keying and playing back sounds. (For podcasting)
description: A soundboard for hot-keying and playing back sounds. (For podcasting)

grade: stable
confinement: strict

parts:
  main:
    source: ./CasterSoundboard
    plugin: qmake
    qt-version: qt5
    after:
      - desktop-qt5
    build-packages:
      - g++
      - qtdeclarative5-dev
      - qt5-default
      - qtmultimedia5-dev

apps:
  castersoundboard:
    command: bin/desktop-launch $SNAP/bin/CasterSoundboard
    #desktop: usr/share/applications/wpcom.desktop
    plugs:
      - home
      - mount-observe
      - network
      - network-bind
      - pulseaudio
      - x11
